### ISSUE TITLE
Sticker button not recolored

### ISSUE THREAD

**Issue by CodeF53** [tazz4843/JetBlack#1]
![image](https://user-images.githubusercontent.com/37855219/133832002-081569f4-143c-4af7-9138-048cf14078c9.png)
TBH I wouldnt mind if the solution to this would be to just hide the sticker button

**Comment by tazz4843** [comment]
Whoops sorry for not seeing this for almost a year now my bad.

Recoloring buttons is a bit of a pain in the ass since there's so many colors. Whenever I do something with them I end up breaking half my other stuff. Plus, it's hard to distinguish the colors in a good way. I don't think I'm going to bother recoloring buttons besides fixing any ones that are broken.

**Comment by CodeF53** [comment]
Considering this was a powercord theme that is pretty fair given powercord is now dead.

**Comment by tazz4843** [comment]
I'm likely going to just switch to developing for Replugged instead since it's basically a Powercord fork, so this will still be alive.
